name: 'DNext - JSON:API'
description: 'The DNext - JSON:API recipe provides a comprehensive setup for creating a decoupled Drupal application using JSON:API and Next'
type: 'Site'

install:
  - basic_auth
  - jsonapi
  - jsonapi_defaults
  - jsonapi_extras
  - jsonapi_image_styles
  - jsonapi_menu_items
  - jsonapi_resources
  - jsonapi_schema
  - image

config:
  actions:
    jsonapi_image_styles.settings:
      simpleConfigUpdate:
        image_styles: ['webp']
