name: 'Headless - JSON:API'
description: 'Headless Drupal with JSON:API'
type: 'Site'

install:
  - jsonapi
  - jsonapi_defaults
  - jsonapi_extras
  - jsonapi_image_styles
  - jsonapi_menu_items
  - jsonapi_resources
  - image
  - next

config:
  actions:
    jsonapi_image_styles.settings:
      simpleConfigUpdate:
        image_styles: ['webp']
